### ISSUE TITLE
解析出现这个异常，是不对吗

### ISSUE THREAD

**Issue by justin-mc-lai** [ganlvtech/php-enphp-decoder#1]
`
$ php bin/decode.php SearchController.class.php out.php
PHP Warning:  gzinflate(): data error in C:\Users\qingmu-523\Desktop\dist\src\Au
toDecoder.php on line 82

Warning: gzinflate(): data error in C:\Users\qingmu-523\Desktop\dist\src\AutoDec
oder.php on line 82
PHP Warning:  explode(): Empty delimiter in C:\Users\qingmu-523\Desktop\dist\src
\AutoDecoder.php on line 82

Warning: explode(): Empty delimiter in C:\Users\qingmu-523\Desktop\dist\src\Auto
Decoder.php on line 82
<?php

namespace Home\Controller;

error_reporting(E_ALL ^ E_NOTICE);
$_SERVER[�] = '��';
$_SERVER[$_SERVER[�]] = explode('|||', gzinflate(substr('�U[oGVU�X
yi��*U        D��4Q�H@[UBZ�w������Ƥʃ�8q!N �D�%&6Ŧ���Ryv7O�gfwZ�B}���s
�!ǖ��zK��$\'��|E
��j�_:[���R��Q�%��F]d@"E0��#�?�����@ZS���&�0u���M@藌 K>Y3t
� ��=�r��t���8אz6����2N;6�6K�����2��FS��Av�c�����$�  r����/�+��BL*�g��\\�/�

`

**Comment by ganlvtech** [comment]
请提供文件的内容，EnPHP 会用到的一个全局变量，这个全局变量是名称不唯一，由于样本不足，我无法预测没见到过的名称。
