### ISSUE TITLE
貌似有点问题

### ISSUE THREAD

**Issue by myitmx** [ganlvtech/php-enphp-decoder#3]
![20190311180741.png](https://i.loli.net/2019/03/11/5c8634ed50f49.png)
貌似解不出来，是我操作问题吗

**Comment by myitmx** [comment]
相关样本已经在吾爱破解论坛提供了
https://www.52pojie.cn/forum.php?mod=viewthread&tid=883976&page=9#pid24464761

**Comment by ganlvtech** [comment]
你直接运行

```bash
php Center.Core.php
```

会不会提示错误？

如果直接运行这个文件都提示错误，那么解码怎么能不错误呢？
