### ISSUE TITLE
对类的处理不是很到位

### ISSUE THREAD

**Issue by maxzhang666** [ganlvtech/php-enphp-decoder#4]
测试了一下类的解码，依旧含有部分乱码
这里有份样本可以测一下
[Setting.zip](https://github.com/ganlvtech/php-enphp-decoder/files/2964719/Setting.zip)

**Comment by ganlvtech** [comment]
不解密的程序能正常运行吗？

根据我的分析这是 EnPHP 的 Bug，加密后的文件并不符合预期，导致解密也不符合预期。这个问题不会被修复。

**Comment by maxzhang666** [comment]
> 不解密的程序能正常运行吗？
> 
> 根据我的分析这是 EnPHP 的 Bug，加密后的文件并不符合预期，导致解密也不符合预期。这个问题不会被修复。

加密后正常运行，没事我就反馈一下

**Comment by ganlvtech** [comment]
Problem has been solved because of the php version used by EnPHP is PHP 5.
